### ISSUE TITLE
Party starts from scratch on hitting home button and Party Unavailable on same WiFi network when someone joins

### ISSUE THREAD

**Issue by Taniamp** [Bezirk-Bosch/party#26]
Steps to reproduce:

1. Host a party, add songs and minimize the application by hitting the home button
2. Invoke the application again
3. Now the party has started from scratch and we need to again set the party name
4. After doing so if someone joins the party from another phone, a pop up is displayed as "Party unavailable!" even after they are connected to the same WiFi network
5. In some case no pop up is displayed as well.

**Comment by neha20priya** [comment]
Resolved
