### ISSUE TITLE
Different Party names 

### ISSUE THREAD

**Issue by Taniamp** [Bezirk-Bosch/party#28]
Steps:
1. Host a party by setting a party name, add music from spotify and start playing the playlist
2. Join the party from another phone
2. Let the host minimize the app by hitting the home button
3. The party starts from scratch but the music will be still playing from background and now enter a different party name and add music from spotify
4. The songs will be added to the previous playlist but the host will be with d different party name and whoever joined with the old party name
5.  No notification is received to the ones who joined the party as well

**Comment by neha20priya** [comment]
Resolved
