### ISSUE TITLE
Guest Can't find a party after relaunching app

### ISSUE THREAD

**Issue by AjaxianK** [Bezirk-Bosch/party#32]
Steps:
1. Device A opens app, hosts a party P
2. Device B opens app, clicks on button "join a party" (party P is visible at this point).
3. Device A goes to background by pressing Home button or choosing another app.

[further info 1.13](https://bezirk.atlassian.net/wiki/pages/editpage.action?pageId=34930733)

**Comment by neha20priya** [comment]
Updated code with changes
