### ISSUE TITLE
App Crashes when host party comes from background after sometime

### ISSUE THREAD

**Issue by AjaxianK** [Bezirk-Bosch/party#33]
Steps:
1. Device A opens app, hosts a party P
2. Device A is locked.
3. Device A is unlocked

[further info 1.14](https://bezirk.atlassian.net/wiki/pages/editpage.action?pageId=34930733)

**Comment by maass-bezirk** [comment]
Do you have a stack trace for the crash?

**Comment by AjaxianK** [comment]
![issue 33](https://cloud.githubusercontent.com/assets/1794664/21200076/acb9c12c-c20b-11e6-8a8a-436fbc314ca3.png)
